version: "3.8"
services:
  mongodb:
    image : mongo
    container_name: mongodb
    environment:
      - user='root'
      - password ='password'
    volumes:
      - ./db:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped